name: universal_downloader
description: "Universal Downloader - a generic media downloader for Linux desktop. Detects the provider from a pasted URL and downloads video + audio streams."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.5.5
  file_selector: ^1.1.0
  crypto: ^3.0.7
  archive: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
